force-app/main/default/objects/whosViewing__e/whosViewing__e.object-meta.xml
<CustomObject>
    <label>whosViewing</label>
    <pluralLabel>whosViewing</pluralLabel>
</CustomObject>

force-app/main/default/objects/whosViewing__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <label>recordId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/whosViewing__e/fields/responseTo__c.field-meta.xml
<CustomField>
    <fullName>responseTo__c</fullName>
    <label>responseTo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/whosViewing__e/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/whosViewing__e/fields/timestamp__c.field-meta.xml
<CustomField>
    <fullName>timestamp__c</fullName>
    <label>timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/whosViewing__e/fields/userId__c.field-meta.xml
<CustomField>
    <fullName>userId__c</fullName>
    <label>userId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/whosViewingController.cls
public class whosViewingController {
    
    @AuraEnabled
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }
    
    @AuraEnabled
    public static string pushViewing(string userId, string recordId, string status, string responseTo){
        string response = '';
        
        Datetime now = system.now();
        
        List<whosViewing__e> viewing = new List<whosViewing__e>();
        viewing.add(new whosViewing__e(
            recordId__c=recordId, 
            userId__c=userId, 
            status__c=status,
            responseTo__c=responseTo,
            timestamp__c=now));
        
        
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(viewing);
        
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
                response = 'success';
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
                response = 'failed';
            }       
        }               
            
            return response ;
        }
    
        


}